export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const CONTACTS_ROUTE = '/contacts'
export const TARIFF_ROUTE = '/tariff'
export const DRIVERS_ROUTE = '/drivers'
export const FEEDBACK_ROUTE = '/feedback'
